### ISSUE TITLE
Misleading report (Reports 0 errors if flow cannot be run)

### ISSUE THREAD

**Issue by joseraya** [charliedowler/gulp-flowtype#21] opened 2015-02-13 07:41 UTC
I copied the example configuration that uses `declarations: './declarations',` and it was reporting `✔ Flow has found 0 errors` even though running flow by hand found some errors.

I have found that the problem was that the flow command was failing with `Error: Command failed: find: ./declarations: No such file or directory`. After creating the declarations directory everything was fine.

**Comment by charliedowler** [comment] 2015-02-13 20:39
Hey @joseraya ,

Sounds like a duplicate of https://github.com/charliedowler/gulp-flowtype/issues/20 which I discovered yesterday.

Will fix asap.

Cheers

**Closed by charliedowler** 2015-02-13 20:39 UTC
Labels: duplicate

**Comment by charliedowler** [comment] 2015-02-13 22:34
@joseraya 

Just realised your issue is similar to https://github.com/charliedowler/gulp-flowtype/issues/20, where the `execFile` error is not being handled properly. I will make sure to handle this issue in the next release.

As for the `No such file or directory` error, I think you've mistakenly put the `declarations` property into your options, this isn't required to run the task. Only use that property if you're using flow declaration files in your checks. Read more [here](http://flowtype.org/docs/declarations.html).

Let me know if I've missed something.

Cheers

**Comment by joseraya** [comment] 2015-02-15 21:48
I think that you are right. I just copied the configuration from the readme without much consideration and the error message drove me crazy for a while.

Thank you very much for answering so quickly.
